Add and correct more test dependencies
- Tests now build and run, but fail due to: java.lang.NoClassDefFoundError: Could not initialize class JvmUnitTestDemoAssetManager and Roborazzi image comparison failure - expected, need to continue to setup test stuff.