Upgrade moduleGraph to 2.9.0
This is necessary for the app to build with Gradle 9.0.0, otherwise the
following Gradle error occurs:

  java.lang.NoSuchMethodError: 'org.gradle.api.Project org.gradle.api.artifacts.ProjectDependency.getDependencyProject()'
        at com.jraska.module.graph.assertion.GradleDependencyGraphFactory.listAllDependencies(GradleDependencyGraphFactory.kt:39)

This is due to jraska/modules-graph-assert#305.